页面刷新的修复
jinmu1/ruoyi pull request #14
Opened 2024-01-27 05:07 UTC by jinmu1

1.修复了导入数据后页面刷新的问题

2024-01-27 08:10 UTC, roundpineapple requested changes
<img width="1381" alt="Screenshot 2024-01-27 at 16 04 08" src="https://github.com/jinmu1/ruoyi/assets/156407020/acc6700c-f138-4a94-88c2-ba72a201aa0f">

导入之后下拉菜单选择之后表单跟图标是坏的。请本地测试完毕改正

2024-01-27 09:44 UTC, jinmu1 commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/ABCAnalyseController.java
我在controller里的DataEntry的属性上增加了JsonProperty来进行json转换

2024-01-27 09:44 UTC, jinmu1 commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/ABCAnalyseController.java
页面上表单重新赋值的代码删除掉了

2024-01-28 02:10 UTC, roundpineapple requested changes

2024-01-28 02:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
>              data:data2,
去掉这行，把line 1623 放到init 后面

2024-01-28 02:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +        $('#bootstrap-table7').bootstrapTable('load',data3);
这里也是同上loadTable6

2024-01-28 02:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +        $('#bootstrap-table8').bootstrapTable('load',data4);
这里也是同上loadTable6

2024-01-28 02:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +        submit();
请加注释每行在干嘛，更新哪个表格或者哪个chart

1, 2, 3谁都看不懂

比如
`submit();  // 重新提交第一个下拉菜单结果，更新bootstrap-table5`

2024-01-28 02:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                            reflash();
这里只需要刷新submit()和reloadX() 

请加注释

2024-01-28 02:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                            reflash();
这里只需要
submit1();
reloadX3();

请加注释在干嘛，123看不懂

2024-01-28 02:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                            reflash();
这里只需要
submit2();
reloadX4();

请加注释在干嘛，123看不懂

2024-01-28 11:34 UTC, jinmu1 commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +        });
将option内的内容放到了boostrap-table里

2024-01-28 11:43 UTC, roundpineapple requested changes

2024-01-28 11:43 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                            //data3重新赋值后，加载与data3相关的调用方法
注释错了吧，是data5重新负值后

2024-01-28 11:43 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                            //data3重新赋值后，加载与data3相关的调用方法
这里也是复制粘贴错了哈

2024-01-28 11:43 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                            //重新加载data2
这里也错了，重新加载data1

2024-01-28 11:43 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                            //data2重新赋值后，加载与data2相关的调用方法
这里注释也错了。

2024-01-28 12:22 UTC, roundpineapple approved these changes

2024-01-28 12:33 UTC, merged