upload，导入方法的重构
jinmu1/ruoyi pull request #21
Opened 2024-01-31 07:58 UTC by jinmu1

将upload方法重构成通用方法，然后再导入按钮直接调用，在页面处理返回的result信息
<img width="1277" alt="ABCJS测试" src="https://github.com/jinmu1/ruoyi/assets/26142135/c95ea128-b154-47df-9f25-6a93ff45816e">

2024-01-31 14:22 UTC, roundpineapple requested changes

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +        btn1: function(index, layero) {
btn1后面的function请在此函数之前单独命名一下，然后这里调用。现在这个nested写法很难读

`btn1: function(index, layero) {
   uploadFileToBackend(index, layero);
}`

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    var currentId = $.common.isEmpty(formId) ? 'importTpl' : formId;
formId没有赋值所以这里直接

`const var currentId = 'importTpl';`

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    var _height = $.common.isEmpty(height) ? "230" : height;
这两行也是毫无意义，一看就是哪里复制粘贴的

请直接给 const var width    和 const var height赋予初始值

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +        type: 1,
请加注释，type: 1在干嘛？
底下的每一行参数都请加注释

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +            if (file == '' || (!file.endsWith('.xls') && !file.endsWith('.xlsx') && !file.endsWith('.csv'))) {
后台并不支持.csv，去掉

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +        content: $('#' + currentId).html(),
这里最好用一个js函数来生成html吧，不然你里面的id名字还有form的名字都不是这个函数控制的但是你这个函数又要调用

你就直接把那个form写到这个函数里吧，这样更robust一点

`var popup_html = "<form ....> <div ...."`
`...`
`content: popup_html`

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    window.layer.open({
这里请加上注释你使用的library连接： https://layui.itze.cn/doc/modules/layer.html

2024-01-31 14:22 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +                        handleImportResult(url,result);//页面的对返回数据的处理方法
这个函数应该作为参数传进来。

importData('abc/importData', updateFirstGroup);

function updateFirstGroup(result) {
   data1 = ...
   data2= ...
   reloadtable...
   submit()
   reloadX()
}

2024-02-01 07:22 UTC, jinmu1 commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    window.layer.open({
已修改

2024-02-01 07:22 UTC, jinmu1 commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +        btn1: function(index, layero) {
已修改

2024-02-01 07:22 UTC, jinmu1 commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
>  </body>
删掉页面的导入的html代码和百度统计代码

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    var _width =  "400";
const var

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    var _height = "230";
const var

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +function importData(url,updateGroup) {
空格，然后注释，
通常传函数会叫做 xx_callback

这里叫做  refresh_data_callback吧

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> + * @param index
注释解释参数please

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    if (file == '' || (!file.endsWith('.xlsx'))) {
!file.endsWith... 前面括号不需要

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +
去掉空格

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +    var loadingIndex = window.layer.load(2, {shade: false});
这里在干嘛？ load(2, 的 2 是什么？

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                <a class="btn btn-info" onclick="importData('system/abc/importData',updateFirstGroup)">
空格

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                    <a class="btn btn-info" onclick="importData('system/abc/importData1',updateSecondGroup)" >
空格

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +                        <a class="btn btn-info" onclick="importData('system/abc/importData2',updateThirdGroup)" >
空格

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +            data3=JSON.parse(result.data.data3);
多了一个tab?

2024-02-01 08:10 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/abc/index.html
> +            $('#bootstrap-table').bootstrapTable('load', data1);
每一行写注释

2024-02-01 08:20 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/static/js/baidie/upload.js
> +        window.layer.msgWarning("请选择后缀为“xlsx”的文件。");
msgWarning方法不存在， 改成alert

<img width="489" alt="Screenshot 2024-02-01 at 16 19 57" src="https://github.com/jinmu1/ruoyi/assets/156407020/8ba83932-025b-4e23-84ac-a82a9027922a">

2024-02-03 06:46 UTC, roundpineapple approved these changes

2024-02-03 07:01 UTC, merged