将List对象转换为json字符串的方法
jinmu1/ruoyi pull request #25
Opened 2024-02-01 06:43 UTC by jinmu1

将所有List对象转换为json字符串的方法，可以返回一个json的字符串给前端
并且做了测试

2024-02-01 07:39 UTC, roundpineapple requested changes

2024-02-01 07:39 UTC, roundpineapple commented on ruoyi-admin/src/test/java/com/ruoyi/web/controller/utils/BaidieUtilsTest.java
> +        String emptyString = BaidieUtils.convertListObjectsToJsonString(data1Entries);
变量名有错

2024-02-01 07:39 UTC, roundpineapple commented on ruoyi-admin/src/test/java/com/ruoyi/web/controller/utils/BaidieUtilsTest.java
> +        assertNotNull(emptyString);
这里需要 assertFalse(result.isEmtpy())

这里不可能是null所以这个测试是无效的

2024-02-01 07:39 UTC, roundpineapple commented on ruoyi-admin/src/test/java/com/ruoyi/web/controller/utils/BaidieUtilsTest.java
> +        assertNotNull(emptyString);
还需要检查一下内容吧。
可以用assertTrue(result.contains("....."));

2024-02-01 07:46 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/ABCAnalyseController.java
> +        String jsonString = BaidieUtils.convertListObjectsToJsonString(data1Entries);
更好的方式是写一个函数with varargs

`public JSONObject generateResponseJson(HashMap<string, Object> jsonKeyToValue) {
    // ...
}`

然后这里直接
`generateResponseJson(new HashMap<String, Object>{"data1": data1Entry, "data2": data2Entry})`

2024-02-01 15:03 UTC, roundpineapple requested changes

2024-02-01 15:03 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/utils/BaidieUtils.java
> +    public static String convertListObjectsToJsonString(List<?> list) throws JsonProcessingException {
把这个函数编程private。在generateResponseJson里面调用

2024-02-01 15:03 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/utils/BaidieUtils.java
> +    public static JSONObject generateResponseJson(HashMap<String, String> jsonKeyToValue) {
改成直接HashMap<String, Object> 这里直接传dataEntry object

2024-02-01 15:03 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/ABCAnalyseController.java
> +            put("data1", BaidieUtils.convertListObjectsToJsonString(data1Entries));
这里没有必要把dataXEntries转换为json string的内部细节写出来，直接传data1Entries，在generateResponseJson函数里面转换。

generateResponseJson应该把所有如何把java object转换成json的逻辑全部封装起来。

主函数负责计算数据，然后把计算好的数据跟对应的key传给工具函数转换就好了，不用知道怎么转换。不用知道该调用哪个函数转化。这才是好的模块化。

而你这里，主函数还一定要知道要调用convertListObjectsToJsonString函数，将来有其它的convertListObjectsToString函数的话，主函数如何知道应该调用谁呢？

2024-02-02 06:53 UTC, roundpineapple requested changes

2024-02-02 06:53 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/ABCAnalyseController.java
> +            put("data1",data1Entries);
空格。

2024-02-02 06:53 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/ABCAnalyseController.java
> +            put("data5",data5Entries);
空格

2024-02-02 06:53 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/utils/BaidieUtils.java
> +    public static String convertListObjectsToJsonString(List<?> list) throws JsonProcessingException {
改为private static

2024-02-02 06:53 UTC, roundpineapple commented on ruoyi-admin/src/test/java/com/ruoyi/web/controller/utils/BaidieUtilsTest.java
> +    public void toEmptyJsonString() throws JsonProcessingException {
这里的unittest需要测试generateResponseJson，而不是这个private method

2024-02-02 07:49 UTC, roundpineapple requested changes

2024-02-02 07:49 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/utils/BaidieUtils.java
> +
把private method放到public methods的后面

2024-02-02 07:49 UTC, roundpineapple commented on ruoyi-admin/src/test/java/com/ruoyi/web/controller/utils/BaidieUtilsTest.java
> +        List<Integer> list1 = new ArrayList<>();
你好歹也测一下你的DataEntry吧。你现在就这么一个地方有个安全检查了，还偷懒

2024-02-02 08:24 UTC, jinmu1 commented on ruoyi-admin/src/test/java/com/ruoyi/web/controller/utils/BaidieUtilsTest.java
> +        List<Integer> list1 = new ArrayList<>();
好的

2024-02-02 14:42 UTC, roundpineapple approved these changes

2024-02-03 04:35 UTC, merged