最新修改1.23
jinmu1/ruoyi pull request #3
Opened 2024-01-23 09:26 UTC by jinmu1

ABC分析的内容

2024-01-23 09:31 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +
麻烦写一下这个controller的整体文档

2024-01-23 09:51 UTC, roundpineapple reviewed
总体上code style上有很多问题，但是功能上你确定这一版本work吗？你的java response目前没有填内容

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +     * ABC出库金额分析的导入数据
please update the comments here 麻烦把文档更新一下，这里不是abc

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +     * ABC出库金额分析的导入数据
请写一下这个post是在干嘛

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +
请把多余的空行删掉

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +        public String getDeliveryDate() {
这里可以用lombok来简化，可以下次来改。先跟你说一下

以后就可以用@Getter @Setter直接减化掉

https://projectlombok.org/features/GetterSetter

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +    class Data1Item {
请把这些数据类放到一个子文件夹里面。
在system/eiq/EIQData1Item.java  等等。

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +    class Data2Item {
没有用到的数据类请不要放到这个pull request里面

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +    class Data4Item {
这里也是，请把这些没有在这个改动里用到的数据类去掉

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +    public AjaxResult importData(MultipartFile file, boolean updateSupport, HttpServletRequest request) throws Exception
这里不是应该return一个你定义好的数据类吗？你底下也并没有填AjaxResult的内容。这个change工作吗？

2024-01-23 09:51 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +        return AjaxResult.success(null);
你没有填任何ajaxResult的内容呀

2024-01-23 09:53 UTC, roundpineapple requested changes
请至少把一下几点改正再merge

1. DataItem* 数据类放到单独的文件夹里面，本次改动不需要的数据类请不要放进来。
2. controller 类的注释请更新
3. 后台的response请填好内容

2024-01-24 11:54 UTC, jinmu1 commented
今天的修改

2024-01-25 07:24 UTC, roundpineapple requested changes
整体上主函数的的可读性需要大幅增加，请把主函数拆成一下的子函数

子函数的名称请选用合理的名称，一读就懂。英文不会的问我

inputData = parseInputFile(...)
data2 = convertToXXData()    
data3 = convertToYYData()
。。。
writeDataToLocalFile(inputData, data2, data3...);

return ..;

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-system/src/main/java/com/ruoyi/system/domain/eiq/Data1Item.java
> +public  class Data1Item {
可以把这些Data*Item的类命名为具体的东西吗？增强代码的可读性。

（这个需要你的专业知识来判单表的名字哈）比如这个类可以叫做 EIQAnalysisInputData, 你可以用intelliJ的Refactor功能来更改类的名字，很快的。

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-system/src/main/java/com/ruoyi/system/domain/eiq/Data2Item.java
> +public class Data2Item {
rename to something like ENQAnalysisData? 你自己决定名字哈

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-system/src/main/java/com/ruoyi/system/domain/eiq/Data3Item.java
> +public  class Data3Item {
重命名一下吧

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +    private static SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
private static final

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +
去掉empty lines please

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +     */
这里请再描述一下具体导入数据之后需要在server本地保存文件还是有数据库的存的动作。这样增强程序的可读性

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-system/src/main/java/com/ruoyi/system/domain/eiq/Data4Item.java
> +package com.ruoyi.system.domain.eiq;
把directory name改成system/data吧，domain有点不知道什么意思

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +        ExcelUtil<Data1Item> util = new ExcelUtil<>(Data1Item.class);
请把38行到41行放到一个private method里面。

private Map<Date, List<Data1Item>> parseInputExcel(MultipartFile file);


主函数里面最好不要放太细小的逻辑，也不要放一些中间变量比如这个util变量，就不属于主函数，请放到parseInputExcel里面去。

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +        Map<String, List<Data1Item>> categorizedMap1 = data1Entries.stream()
what is categorizedMap1。请把变量名命名为一看就明白是在干嘛的名字。现在的代码的可读性太差

2024-01-25 07:24 UTC, roundpineapple commented on ruoyi-admin/src/main/java/com/ruoyi/web/controller/system/EIQAnalyseController.java
> +        ObjectMapper objectMapper = new ObjectMapper();
115行到133行请放进private method

2024-01-25 07:52 UTC, roundpineapple requested changes
html和javascript的东西也是同样的问题
1. 没有跟abc重用function
2. 主函数太长

2024-01-25 07:52 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/eiq/index.html
> +                    url: '/system/abc/importData',
这里还是abc，应该是eiq

2024-01-25 07:52 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project1/ass3/eiq/index.html
> +    function importData() {
整个function应该跟abc/index.html的重用。你把这个function放到一个公共的jcommonUtils.s 文件里面然后在这里重用吧

<head>
      <script type = "text/javascript" src="commonUtils.js"></script>
   </head>

2024-01-25 07:52 UTC, roundpineapple commented on ruoyi-admin/src/main/resources/templates/system/project11/ass3/eiq/index.html
> +                        if (result.code == web_status.SUCCESS) {
这个里面的javascript也应该放到自己的子函数里面，最好放到单独的.js 文件里面

2024-01-26 04:47 UTC, closed without merging